// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OpenShipsAPI.Infrastructure.Database;

#nullable disable

namespace OpenShipsAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260904142746_AddAisPositionTables")]
    partial class AddAisPositionTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OpenShipsAPI.Domain.Destination.ShipDestination", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("FirstSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("From")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Mmsi")
                        .HasColumnType("bigint");

                    b.Property<string>("Raw")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RouteType")
                        .HasColumnType("integer");

                    b.Property<string>("To")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Mmsi", "Raw")
                        .IsUnique();

                    b.ToTable("ShipDestinations");
                });

            modelBuilder.Entity("OpenShipsAPI.Infrastructure.Database.Models.CurrentAisPosition", b =>
                {
                    b.Property<int>("Mmsi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Mmsi"));

                    b.Property<double?>("Cog")
                        .HasColumnType("double precision");

                    b.Property<int?>("CommunicationState")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("EventTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Heading")
                        .HasColumnType("integer");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<int>("License")
                        .HasColumnType("integer");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<int>("MessageType")
                        .HasColumnType("integer");

                    b.Property<int?>("NavigationStatus")
                        .HasColumnType("integer");

                    b.Property<bool?>("PositionAccuracy")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Raim")
                        .HasColumnType("boolean");

                    b.Property<double?>("RateOfTurn")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RepeatIndicator")
                        .HasColumnType("integer");

                    b.Property<double?>("Sog")
                        .HasColumnType("double precision");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("SourceMessageId")
                        .HasColumnType("text");

                    b.Property<int?>("Spare")
                        .HasColumnType("integer");

                    b.Property<int?>("SpecialManoeuvreIndicator")
                        .HasColumnType("integer");

                    b.Property<bool?>("Valid")
                        .HasColumnType("boolean");

                    b.HasKey("Mmsi");

                    b.HasIndex("EventTimestamp");

                    b.ToTable("CurrentAisPositions");
                });

            modelBuilder.Entity("OpenShipsAPI.Infrastructure.Database.Models.HistoricalAisPosition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double?>("Cog")
                        .HasColumnType("double precision");

                    b.Property<int?>("CommunicationState")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("EventTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Heading")
                        .HasColumnType("integer");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<int>("License")
                        .HasColumnType("integer");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<int>("MessageType")
                        .HasColumnType("integer");

                    b.Property<int>("Mmsi")
                        .HasColumnType("integer");

                    b.Property<int?>("NavigationStatus")
                        .HasColumnType("integer");

                    b.Property<bool?>("PositionAccuracy")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Raim")
                        .HasColumnType("boolean");

                    b.Property<double?>("RateOfTurn")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RepeatIndicator")
                        .HasColumnType("integer");

                    b.Property<double?>("Sog")
                        .HasColumnType("double precision");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("SourceMessageId")
                        .HasColumnType("text");

                    b.Property<int?>("Spare")
                        .HasColumnType("integer");

                    b.Property<int?>("SpecialManoeuvreIndicator")
                        .HasColumnType("integer");

                    b.Property<bool?>("Valid")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Mmsi", "EventTimestamp");

                    b.ToTable("HistoricalAisPositions");
                });
#pragma warning restore 612, 618
        }
    }
}
