// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OpenShipsAPI.Infrastructure.Database;

#nullable disable

namespace OpenShipsAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260907132220_AddDestinationPortReferences")]
    partial class AddDestinationPortReferences
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OpenShipsAPI.Domain.Destination.ShipDestination", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("FirstSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("From")
                        .HasColumnType("text");

                    b.Property<int?>("FromPortId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MatchedBy")
                        .HasColumnType("integer");

                    b.Property<int>("Mmsi")
                        .HasColumnType("integer");

                    b.Property<string>("Raw")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RouteType")
                        .HasColumnType("integer");

                    b.Property<string>("To")
                        .HasColumnType("text");

                    b.Property<int?>("ToPortId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FromPortId");

                    b.HasIndex("ToPortId");

                    b.HasIndex("Mmsi", "Raw")
                        .IsUnique();

                    b.ToTable("ShipDestinations");
                });

            modelBuilder.Entity("OpenShipsAPI.Infrastructure.Database.Models.CurrentAisPosition", b =>
                {
                    b.Property<int>("Mmsi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Mmsi"));

                    b.Property<double?>("Cog")
                        .HasColumnType("double precision");

                    b.Property<int?>("CommunicationState")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("EventTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Heading")
                        .HasColumnType("integer");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<int>("License")
                        .HasColumnType("integer");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<int>("MessageType")
                        .HasColumnType("integer");

                    b.Property<int?>("NavigationStatus")
                        .HasColumnType("integer");

                    b.Property<bool?>("PositionAccuracy")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Raim")
                        .HasColumnType("boolean");

                    b.Property<double?>("RateOfTurn")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RepeatIndicator")
                        .HasColumnType("integer");

                    b.Property<double?>("Sog")
                        .HasColumnType("double precision");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("SourceMessageId")
                        .HasColumnType("text");

                    b.Property<int?>("Spare")
                        .HasColumnType("integer");

                    b.Property<int?>("SpecialManoeuvreIndicator")
                        .HasColumnType("integer");

                    b.Property<bool?>("Valid")
                        .HasColumnType("boolean");

                    b.HasKey("Mmsi");

                    b.HasIndex("EventTimestamp");

                    b.ToTable("CurrentAisPositions");
                });

            modelBuilder.Entity("OpenShipsAPI.Infrastructure.Database.Models.HistoricalAisPosition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double?>("Cog")
                        .HasColumnType("double precision");

                    b.Property<int?>("CommunicationState")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("EventTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Heading")
                        .HasColumnType("integer");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<int>("License")
                        .HasColumnType("integer");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<int>("MessageType")
                        .HasColumnType("integer");

                    b.Property<int>("Mmsi")
                        .HasColumnType("integer");

                    b.Property<int?>("NavigationStatus")
                        .HasColumnType("integer");

                    b.Property<bool?>("PositionAccuracy")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Raim")
                        .HasColumnType("boolean");

                    b.Property<double?>("RateOfTurn")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RepeatIndicator")
                        .HasColumnType("integer");

                    b.Property<double?>("Sog")
                        .HasColumnType("double precision");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("SourceMessageId")
                        .HasColumnType("text");

                    b.Property<int?>("Spare")
                        .HasColumnType("integer");

                    b.Property<int?>("SpecialManoeuvreIndicator")
                        .HasColumnType("integer");

                    b.Property<bool?>("Valid")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Mmsi", "EventTimestamp");

                    b.ToTable("HistoricalAisPositions");
                });

            modelBuilder.Entity("OpenShipsAPI.Infrastructure.Database.Models.PortAliasDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PortId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PortId", "Alias")
                        .IsUnique();

                    b.ToTable("PortAliases");
                });

            modelBuilder.Entity("OpenShipsAPI.Infrastructure.Database.Models.PortDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Function")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameWoDiacritics")
                        .HasColumnType("text");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<string>("Subregion")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Country", "Location")
                        .IsUnique();

                    b.HasIndex("Latitude", "Longitude");

                    b.ToTable("Ports");
                });

            modelBuilder.Entity("OpenShipsAPI.Infrastructure.Database.Models.StaticShipDataAis", b =>
                {
                    b.Property<int>("Mmsi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Mmsi"));

                    b.Property<float?>("Beam")
                        .HasColumnType("real");

                    b.Property<string>("CallSign")
                        .HasColumnType("text");

                    b.Property<float?>("Dim_A")
                        .HasColumnType("real");

                    b.Property<float?>("Dim_B")
                        .HasColumnType("real");

                    b.Property<float?>("Dim_C")
                        .HasColumnType("real");

                    b.Property<float?>("Dim_D")
                        .HasColumnType("real");

                    b.Property<float?>("Draught")
                        .HasColumnType("real");

                    b.Property<DateTimeOffset?>("Eta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("EventTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ImoNumber")
                        .HasColumnType("integer");

                    b.Property<float?>("Length")
                        .HasColumnType("real");

                    b.Property<int>("License")
                        .HasColumnType("integer");

                    b.Property<int>("MessageType")
                        .HasColumnType("integer");

                    b.Property<string>("RawDestination")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ShipName")
                        .HasColumnType("text");

                    b.Property<int?>("ShipType")
                        .HasColumnType("integer");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("SourceMessageId")
                        .HasColumnType("text");

                    b.HasKey("Mmsi");

                    b.HasIndex("ImoNumber");

                    b.HasIndex("ShipType");

                    b.ToTable("StaticShipData");
                });

            modelBuilder.Entity("OpenShipsAPI.Domain.Destination.ShipDestination", b =>
                {
                    b.HasOne("OpenShipsAPI.Infrastructure.Database.Models.PortDb", "FromPort")
                        .WithMany()
                        .HasForeignKey("FromPortId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OpenShipsAPI.Infrastructure.Database.Models.PortDb", "ToPort")
                        .WithMany()
                        .HasForeignKey("ToPortId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FromPort");

                    b.Navigation("ToPort");
                });

            modelBuilder.Entity("OpenShipsAPI.Infrastructure.Database.Models.PortAliasDb", b =>
                {
                    b.HasOne("OpenShipsAPI.Infrastructure.Database.Models.PortDb", "Port")
                        .WithMany("Aliases")
                        .HasForeignKey("PortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Port");
                });

            modelBuilder.Entity("OpenShipsAPI.Infrastructure.Database.Models.PortDb", b =>
                {
                    b.Navigation("Aliases");
                });
#pragma warning restore 612, 618
        }
    }
}
